### ISSUE TITLE
Vector optimization

### ISSUE THREAD

**Issue by EUTW06** [yukistavailable/FontCLIP#3]
do you have the checkpoint file for vector optimization? thank you

**Comment by EUTW06** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '../model_checkpoints/ViT-B_32_bce_lora_t-qkvo_256-1024.0_91011_batch64_aug50_cj200_lbound_of_scale0.35_max_attr_num_3_random_p_num_10000_geta0.2_use_negative_lr0.0002-0.1_image_file_dir.pt'

I running vector optimization and then this shows up

**Comment by EUTW06** [comment]
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from trains.trainer import Trainer
  File "C:\Users\user\Desktop\Wystem\FontCLIP\trains\trainer.py", line 21, in <module>
    from evals.evaluate_tools import (
  File "C:\Users\user\Desktop\Wystem\FontCLIP\evals\evaluate_tools.py", line 283, in <module>
    assert user_choice[3] in font_names
AssertionError

and when I try to finetune, I found out that font_names doesn't includes lots of names.
only have 148 fonts in all_font_to_attribute_values.json but 201 fonts in estimatedAttributes.csv

**Comment by AI091** [comment]
Hello, @EUTW06  currently running into the same issue. Did you find out a fix for this?

**Comment by yukistavailable** [comment]
Hi @AI091, apparently [gwfonts.zip ](https://www.dgp.toronto.edu/~donovan/font/)lacks many font files necessary for fine-tuning CLIP.
Specifically, you need to download the following fonts manually to gwfonts directory.
```
['ARSMaquetteWebOne', 'Aldrich', 'AnonymousPro', 'ArialRoundedMTBold', 'ArialUnicodeMS', 'Bello-Pro', 'Bevan', 'Brevia-Regular', 'BubblerOne', 'CabinCondensed', 'Calluna-Regular', 'CenturyGothic', 'Damion', 'Fenix', 'FingerPaint', 'FrancoisOne-Regular', 'Frijole', 'Futura-Medium', 'GEInspira', 'GFSNeohellenic-Italic', 'GentiumBasic', 'GentiumBasic-Bold', 'GentiumBasic-BoldItalic', 'GillSansStd', 'GillSansStd-Bold', 'GillSansStd-BoldItalic', 'HoeflerText-Regular', 'IM_FELL_English_Roman', 'IM_FELL_French_Canon_Roman', 'JustAnotherHand-Regular', 'LeagueGothic', 'LucidaSansStd', 'MavenProBlack', 'Merriweather', 'Muli', 'OldStandardTT-Regular', 'OpenSans-CondensedLight', 'PTSans-Caption', 'PTSerif-BoldItalic', 'Palatino-Roman', 'Philosopher', 'Rokkitt', 'Satisfy', 'SourceSansPro-LightIt', 'TenorSans', 'Tinos', 'TitanOne', 'TitilliumWeb-ThinItalic', 'Trochut', 'Tulpen', 'Voltaire', 'YanoneTagesschrift']
```

**Comment by yukistavailable** [comment]
Here is a list of fonts and their download website

ARSMaquetteWebOne https://eng.m.fontke.com/font/22558406/download/
Aldrich https://fonts.google.com/specimen/Aldrich
AnonymousPro https://fonts.google.com/specimen/Anonymous+Pro
ArialRoundedMTBold https://online-fonts.com/fonts/arial-rounded-mt-bold
ArialUnicodeMS https://www.moedict.tw/fonts/truetype/arial/
Bello-Pro https://globalfonts.pro/font/bello-pro
Bevan https://fonts.google.com/specimen/Bevan
Brevia-Regular https://befonts.com/brevia-font-family.html
BubblerOne https://fonts.google.com/specimen/Bubbler+One
CabinCondensed https://fonts.google.com/specimen/Cabin+Condensed
Calluna-Regular https://freefontsfamily.net/calluna-font-free-download/
CenturyGothic https://freefontsfamily.net/century-gothic-font-family/
Damion https://fonts.google.com/specimen/Damion
Fenix https://fonts.google.com/specimen/Fenix
FingerPaint https://fonts.google.com/specimen/Finger+Paint
FrancoisOne-Regular https://fonts.google.com/specimen/Francois+One
Frijole https://fonts.google.com/specimen/Frijole
Futura-Medium https://font.download/font/futura-medium
GEInspira https://font.download/font/ge-inspira
GFSNeohellenic-Italic https://www.whatfontis.com/GFSNeohellenic-Italic.font
GentiumBasic https://www.1001fonts.com/gentium-basic-font.html
GentiumBasic-Bold https://www.1001fonts.com/gentium-basic-font.html
GentiumBasic-BoldItalic https://www.1001fonts.com/gentium-basic-font.html
GillSansStd https://font.download/font/gill-sans-std
GillSansStd-Bold https://font.download/font/gill-sans-std
GillSansStd-BoldItalic https://font.download/font/gill-sans-std
HoeflerText-Regular https://fontsgeek.com/fonts/Hoefler-Text-Regular
IM_FELL_English_Roman https://fonts.google.com/specimen/IM+Fell+English
IM_FELL_French_Canon_Roman https://fonts.google.com/specimen/IM+Fell+French+Canon
JustAnotherHand-Regular https://fonts.google.com/specimen/Just+Another+Hand
LeagueGothic https://fonts.google.com/specimen/League+Gothic
LucidaSansStd https://globalfonts.pro/font/lucida-sans-std
MavenProBlack https://fonts2u.com/maven-pro-black.font
Merriweather https://fonts.google.com/specimen/Merriweather
Muli https://font.download/font/muli-2
OldStandardTT-Regular https://fonts.google.com/specimen/Old+Standard+TT
OpenSans-CondensedLight https://fonts.adobe.com/fonts/muli
PTSans-Caption https://fonts.google.com/specimen/PT+Serif
PTSerif-BoldItalic https://fonts.google.com/specimen/PT+Serif
Palatino-Roman https://font.download/font/palatino
Philosopher https://fonts.google.com/specimen/Philosopher
Rokkitt https://fonts.google.com/specimen/Rokkitt
Satisfy https://fonts.google.com/specimen/Satisfy
SourceSansPro-LightIt https://ja.fonts2u.com/source-sans-pro-light.%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88
TenorSans https://fonts.google.com/specimen/Tenor+Sans
Tinos https://fonts.google.com/specimen/Tinos
TitanOne https://fonts.google.com/specimen/Titan+One
TitilliumWeb-ThinItalic https://fonts.google.com/specimen/Titillium+Web
Trochut https://fonts.google.com/specimen/Trochut
Tulpen https://fonts.google.com/specimen/Tulpen+One
Voltaire https://fonts.google.com/specimen/Voltaire
YanoneTagesschrift https://www.wfonts.com/font/yanone-tagesschrift

**Comment by AI091** [comment]
@yukistavailable  Thank you a lot for your help, would you mind providing a fine-tuned checkpoint for FontClip?

**Comment by yukistavailable** [comment]
@AI091 
I put the .pt file [here](https://drive.google.com/file/d/1Tym7rAIuaGr6Gv-gZRSJmPstQjOWPgl1/view?usp=drive_link)
